SHARED CONST NUM_ASTEROIDS = 12

SHARED CONST SPR_NR_PLAYER = 0
SHARED CONST SPR_NR_POI = 13
SHARED CONST SPR_NR_BULLET = 14
SHARED CONST SPR_NR_TORPEDO = 15

SHARED CONST ZONE_NONE          = $00
SHARED CONST ZONE_PORTAL        = $ee
SHARED CONST ZONE_STAR          = $77
SHARED CONST ZONE_MISSILE_SILO  = $aa
SHARED CONST ZONE_AI            = $88

SHARED CONST PLAYER_SX = 127
SHARED CONST PLAYER_SY = 100

SHARED CONST STATUS_GOLD = 1
SHARED CONST STATUS_METAL = 2
SHARED CONST STATUS_FUEL = 4
SHARED CONST STATUS_OXYGEN = 8
SHARED CONST STATUS_ARMOR = 16
